#ifndef PROTOCOLMANAGER_GLOBAL_H
#define PROTOCOLMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROTOCOLMANAGER_LIBRARY)
#  define PROTOCOLMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROTOCOLMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROTOCOLMANAGER_GLOBAL_H
